### ISSUE TITLE
Assignment action failing

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6008]
https://github.com/meltano/meltano/runs/6734178377?check_suite_focus=true

![image](https://user-images.githubusercontent.com/18150651/171967003-9fa6189c-bfdf-4070-a5d9-3783899d599a.png)

@tayloramurphy - fyi

**Comment by tayloramurphy** [comment]
@aaronsteers this should have been fixed via https://github.com/meltano/meltano/pull/5993 can you confirm?

**Comment by aaronsteers** [comment]
Still failing. This one is just 15 minutes old as of now: https://github.com/meltano/meltano/pull/6016

**Comment by aaronsteers** [comment]
Muted now as of #6007, but should still be addressed.
