### ISSUE TITLE
docs: NO_COLOR not coming up in docs search

### ISSUE THREAD

**Issue by visch** [meltano/meltano#7281]
### Meltano Version

N/A

### Python Version

NA

### Bug scope

Other

### Operating System

NA

### Description

https://github.com/meltano/meltano/blob/e71e5b48047274b0b9f331ca3aa56e94c7447e7a/docs/src/_reference/command-line-interface.md

https://docs.meltano.com/reference/command-line-interface#global-configuration 

Slack discussion: https://meltano.slack.com/archives/CMN8HELB0/p1675779076487979

Searching for COLOR doesn't come up on the docs site. I'm not sure why (I tried NO_COLOR as well), maybe an algolia thing?

**Comment by tayloramurphy** [comment]
@edgarrmondragon suggests it's possibly b/c it's in a list and not in a header. I'll make a PR to get an update for it.

**Comment by WillDaSilva** [comment]
Possibly addressed by #7282

**Comment by tayloramurphy** [comment]
This doesn't solve the problem for all possible searches, but for no_color it's solved.
